# Generated by Django 5.2.8 on 2025-11-15 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(db_index=True, help_text='Which menu this item belongs to. Items in the same menu form a tree.', max_length=100)),
                ('title', models.CharField(help_text='The text that will appear for this menu item.', max_length=200)),
                ('url', models.CharField(blank=True, help_text='Direct URL for this menu item (like /about/). Leave blank if using a named URL.', max_length=500)),
                ('named_url', models.CharField(blank=True, help_text="Django named URL (like 'home'). Used if no direct URL is provided.", max_length=200)),
                ('named_url_kwargs', models.JSONField(blank=True, help_text='Optional parameters for the named URL, e.g., {"id": 5}.', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order. Items with lower numbers appear first.')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='If checked, this menu item will open in a new browser tab.')),
                ('image', models.URLField(blank=True, help_text='Optional image for this menu item. Will use a default placeholder if empty.')),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent menu item. Leave blank if this is a top-level item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.menuitem')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
